/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_digidactylus_oroserver_JNIWrap */

#ifndef _Included_com_digidactylus_oroserver_JNIWrap
#define _Included_com_digidactylus_oroserver_JNIWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_digidactylus_oroserver_JNIWrap
 * Method:    callAnalysisJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_digidactylus_oroserver_JNIWrap_callAnalysisJNI
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
