/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_methority_btbrowser2_JNIWrap */

#ifndef _Included_com_methority_btbrowser2_JNIWrap
#define _Included_com_methority_btbrowser2_JNIWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_methority_btbrowser2_JNIWrap
 * Method:    callAnalysisJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_methority_btbrowser2_JNIWrap_callAnalysisJNI
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
